"""AIGC core domain models and provider interfaces."""

from aigc_core.config import AppSettings, get_settings
from aigc_core.models import (
    Asset,
    AssetType,
    Character,
    GenerationStatus,
    ModelTier,
    Platform,
    Project,
    ProjectStatus,
    ReviewDecision,
    ReviewGate,
    ReviewStatus,
    Scene,
    Shot,
    ShotType,
    Story,
)
from aigc_core.os_models import (
    Approval,
    ApprovalStatus,
    ContentItem,
    CostRecord,
    CostType,
    ExportRecord,
    GenerationRecord,
    KnowledgeBase,
    ProjectType,
    Task,
    TaskStatus,
    VersionRecord,
    Workspace,
)
from aigc_core.pipeline import Pipeline
from aigc_core.provider import (
    BaseProvider,
    GenerationRequest,
    GenerationResult,
    ImageProvider,
    MusicProvider,
    ProviderConfig,
    SfxProvider,
    SubtitleProvider,
    TtsProvider,
    VideoProvider,
)
from aigc_core.registry import LlmProviderAdapter, ProviderRegistry
from aigc_core.storage import ProjectStorage

__all__ = [
    "AppSettings",
    "Approval",
    "ApprovalStatus",
    "ContentItem",
    "CostRecord",
    "CostType",
    "ExportRecord",
    "GenerationRecord",
    "KnowledgeBase",
    "LlmProviderAdapter",
    "ProjectStorage",
    "ProjectType",
    "ProviderRegistry",
    "Task",
    "TaskStatus",
    "VersionRecord",
    "Workspace",
    "get_settings",
    "Asset",
    "AssetType",
    "Character",
    "GenerationStatus",
    "ModelTier",
    "Platform",
    "Pipeline",
    "Project",
    "ProjectStatus",
    "ReviewDecision",
    "ReviewGate",
    "ReviewStatus",
    "Scene",
    "Shot",
    "ShotType",
    "Story",
    "BaseProvider",
    "GenerationRequest",
    "GenerationResult",
    "ImageProvider",
    "MusicProvider",
    "ProviderConfig",
    "SfxProvider",
    "SubtitleProvider",
    "TtsProvider",
    "VideoProvider",
]
